[project]
name = "airbnb-with-dbt-and-snowflake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster-dbt>=0.27.13",
    "dagster-webserver>=1.11.13",
    "dbt-duckdb>=1.9.6",
    "dbt-snowflake==1.9.0",
]
